
version: '3'

services:

  photos:
    build: ./
    depends_on:
      - 'db'
    ports:
      - '3306:3306'

  db:
    image: mysql:5.7 
    environment:
      MYSQL_DATABASE: 'photos'
      MYSQL_ROOT_PASSWORD: 'default'
    volumes: 
    - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql